# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sat, 01 Dec 2018 13:11:33 +0000
*               @ALL          1
*               @user         8
