<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Tue, 25 Dec 2018 12:06:01 +0100
 */

$conf['title'] = 'GitHubDocuWiki';
$conf['lang'] = 'ca';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'cc-by';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';

// end auto-generated content
