<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Sat, 01 Dec 2018 20:32:44 +0100
 */

$conf['title'] = 'GitHubDocuWiki';
$conf['lang'] = 'es';
$conf['template'] = 'LotarProject-dokuwiki-template-bootstrap3-119aa21';
$conf['license'] = 'cc-by';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';

// end auto-generated content
