<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Thu, 20 Dec 2018 18:52:26 +0100
 */

$conf['title'] = 'GitHubDocuWiki';
$conf['lang'] = 'es';
$conf['template'] = 'flat';
$conf['license'] = 'cc-by';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';

// end auto-generated content
