<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Sat, 01 Dec 2018 13:11:33 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
